spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gimlee

gimlee:
  ads:
    category:
      sync:
        enabled: false
  auth:
    rest:
      unsecured-paths: /auth/login,/auth/register
      jwt:
        issuer: gimlee
        key: testkey
