global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gimlee-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['APP_IP_1:8080', 'APP_IP_2:8080'] # These should be replaced by actual IPs or service discovery

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['APP_IP_1:9100', 'APP_IP_2:9100', 'DB_IP:9100', 'WALLET_IP:9100']
